### ISSUE TITLE
Listing contexts fails when managing a large number of contexts

### ISSUE THREAD

**Issue by DmytroKozlovskyi** [mrolla/terraform-provider-circleci#43] opened 2021-03-12 14:09 UTC
With growing number of contexts and variables in CircleCi, we are getting more often this error:
`Error: failed to load context list: Non-nullable field was null.
Something unexpected happened.`

Set `-parallelism=1` for terraform plan is helped for some time, but after add more new contexts, we started to see this error again.

Also, after add 18 contexts via terraform, we got email from CircleCi support with request to explain why we produce so many requests  to CircleCi v1 API and have recommended to switch to v2 REST API:
https://circleci.com/docs/api/v2/#tag/Context

**Comment by bendrucker** [comment] 2021-03-12 16:31
The context feature uses their GraphQL API which isn't officially supported. I'm aware of the added REST support for contexts (finally!) but haven't had a chance to investigate client support and switch here.

**Comment by bendrucker** [comment] 2021-03-12 17:37
This shouldn't be too much trouble:

https://github.com/CircleCI-Public/circleci-cli/blob/master/api/context_rest.go

Might even be able to get to it today, since I'm coincidentally working on some refactoring some CircleCI contexts/vars right now. The REST API does have proper support for fetching a context by ID:

https://circleci.com/docs/api/v2/#operation/getContext

Whereas GraphQL, based on the implementation I borrowed from CircleCI's CLI, only supported listing contexts, and required client-side filtering.

Kinda wild that Circle falls over with that number of requests, but perhaps not so surprising considering contexts were available with no API and then an "unofficial" API for years. Better late than never!

**Comment by DmytroKozlovskyi** [comment] 2021-03-12 17:51
> Might even be able to get to it today, since I'm coincidentally working on some refactoring some CircleCI contexts/vars right now.

Oh, It's would be grate. Thank you @bendrucker

**Comment by bendrucker** [comment] 2021-03-12 18:07
Started on this in https://github.com/mrolla/terraform-provider-circleci/pull/44. I want to convert everything over to v2 (including things that were on REST v1). Should definitely have a tested PR up today, so you can expect this to be released in the next week or two.

**Comment by bendrucker** [comment] 2021-03-13 00:48
A mixed update for you on this. I did a bunch of work to port everything over to API v2. While I want to be respectful to the people at CircleCI who are working hard on this stuff, there are serious, obvious quality problems with this API. I'm working through a long list of failing acceptance tests and am filing bug reports on Circle's discussion board as I identify the causes.

This was the first one:

https://discuss.circleci.com/t/api-v2-malformed-json-bodies-returned-on-400s/39393/2

I expected to be able to use Circle's REST client from their CLI, similar to how I borrowed the GraphQL client from the same place. Instead, I'm finding myself inlining almost all of the client functionality over seemingly small but critical issues, like the one above, or their `CreateContext` method not actually returning the created context (and its ID). 

I am a CircleCI customer via @takescoop and will reach out to support to try to escalate this a bit. If you could also mention it on your open support thread that might help as well. Feel free to link them here or to my discussion threads.

**Comment by DmytroKozlovskyi** [comment] 2021-03-14 09:36
Hi, @bendrucker . Thanks for your work. I've asked CircleCi support for help in our support thread. Will back, when got a response.

**Comment by DmytroKozlovskyi** [comment] 2021-03-19 15:48
Hi, @bendrucker I've got response from CircleCi with same message actually which they have posted in your support thread https://discuss.circleci.com/t/api-v2-malformed-json-bodies-returned-on-400s/39393/4

Also, I've checked this case and it works for me via curl request:
`curl --request POST \   
  --url https://circleci.com/api/v2/context \
  --header 'Circle-Token: REDACTED' \
  --header 'content-type: application/json'  \
  --header 'Accept: application/json' \
  --data '{"name":"context-test","owner":{"slug":"gh/myorg","type":"organization"}}'
{"message":"A context named context-test already exists."}`

Also, have checked with not existed context and I see id for created context in response:
`{"name":"context-test2","id":"764177b6-e38b-4650-adea-323555614ab1","created_at":"2021-03-19T15:45:20.762Z"}`

Please, check when you have time. Also, do you have other blockers?

**Comment by bendrucker** [comment] 2021-03-19 17:10
Yep I'll look into it. This was using their own API client from their CLI. I just have to work through the acceptance tests and figure things out. We're somewhat hamstrung here by the lack of an official API client to rely on. Thought that the package in their CLI would work. It worked pretty flawlessly on the GraphQL side (despite lack of official support) but has been a bit less consistent on the REST side, perhaps because that's not actually hooked up in their CLI yet.

Should have some more free time to work through more acceptance tests today. Will continue to update the PR with notes.

**Comment by DmytroKozlovskyi** [comment] 2021-03-31 13:09
Hi, @bendrucker 
Have built your last changes from circleci-api-v2 branch and it works incredibly fast and without errors so far.  Only one warning pop up on each plan: 
```
Warning: "graphql_url": [DEPRECATED] CircleCI's v2 REST API has replaced the GraphQL API in this provider. This attribute is unused and will be removed in the next major version.
```

**Closed** 2021-05-06 17:53 UTC
